name: (Pre)Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to create release from"
        required: true
        default: "main"
        type: choice
        options:
          - main
          - develop
      tag:
        description: "Release tag (leave empty to auto-bump via GitVersion)"
        required: false
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0.0, v20.15.10

permissions:
  contents: write # Needed for creating GitHub releases

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for GitVersion
          ref: ${{ github.event.inputs.branch }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: "6.x"

      - name: Display release information
        run: |
          BRANCH="${{ github.event.inputs.branch }}"
          echo "🚀 Creating release from branch: $BRANCH"
          case $BRANCH in
            main)
              echo "📦 Release type: Stable Release"
              ;;
            develop)
              echo "🧪 Release type: Beta Pre-release"
              ;;
            *)
              echo "⚠️ Release type: Custom branch release"
              ;;
          esac

      - name: Debug git and environment info
        run: |
          echo "🔍 Git and Environment Debug Information:"
          echo "  Current git branch: $(git branch --show-current)"
          echo "  Git HEAD: $(git rev-parse HEAD)"
          echo "  Git status: $(git status --porcelain)"
          echo "  GITHUB_REF: ${{ github.ref }}"
          echo "  GITHUB_HEAD_REF: ${{ github.head_ref }}"
          echo "  GITHUB_REF_NAME: ${{ github.ref_name }}"
          echo "  Selected branch input: ${{ github.event.inputs.branch }}"
          echo "  Computed branch: ${{ github.event.inputs.branch }}"
          echo "  Git remote branches:"
          git branch -r
          echo ""

      - name: Force checkout to correct branch
        run: |
          TARGET_BRANCH="${{ github.event.inputs.branch }}"
          echo "🔧 Ensuring we're on the correct branch: $TARGET_BRANCH"

          # First, make sure we have the latest refs
          git fetch origin

          # Check if branch exists locally, if not create it from origin
          if ! git show-ref --verify --quiet refs/heads/$TARGET_BRANCH; then
            echo "Creating local branch $TARGET_BRANCH from origin/$TARGET_BRANCH"
            git checkout -b "$TARGET_BRANCH" "origin/$TARGET_BRANCH"
          else
            echo "Checking out existing local branch $TARGET_BRANCH"
            git checkout "$TARGET_BRANCH"
            # Make sure it's up to date with origin
            git reset --hard "origin/$TARGET_BRANCH"
          fi

          echo "✅ Current branch: $(git branch --show-current)"
          echo "✅ Current HEAD: $(git rev-parse HEAD)"
          echo "✅ Origin HEAD for $TARGET_BRANCH: $(git rev-parse origin/$TARGET_BRANCH)"

      - name: Prepare GitVersion environment
        run: |
          TARGET_BRANCH="${{ github.event.inputs.branch }}"
          echo "🔧 Preparing GitVersion for branch: $TARGET_BRANCH"

          # Ensure we're definitely on the target branch for GitVersion
          CURRENT_BRANCH=$(git branch --show-current)
          if [[ "$CURRENT_BRANCH" != "$TARGET_BRANCH" ]]; then
            echo "❌ Branch mismatch! Current: $CURRENT_BRANCH, Expected: $TARGET_BRANCH"
            exit 1
          fi

          echo "✅ Confirmed on correct branch: $CURRENT_BRANCH"

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2
        with:
          useConfigFile: true
          updateAssemblyInfo: true
          configFilePath: GitVersion.yml
          additionalArguments: "/overrideconfig mode=ContinuousDeployment /b ${{ github.event.inputs.branch }}"
        env:
          # Set GitVersion to use the current checked out branch
          GITVERSION_OVERRIDE_BRANCH: ${{ github.event.inputs.branch }}

      - name: Display version information
        run: |
          SELECTED_BRANCH="${{ github.event.inputs.branch }}"
          echo "📋 Branch Information:"
          echo "  Selected branch: $SELECTED_BRANCH"
          echo "  Current git branch: $(git branch --show-current)"
          echo "  Git HEAD ref: $(git symbolic-ref HEAD 2>/dev/null || echo 'detached HEAD')"
          echo ""
          echo "📋 GitVersion Results:"
          echo "  SemVer: ${{ steps.gitversion.outputs.semVer }}"
          echo "  FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
          echo "  NuGetVersion: ${{ steps.gitversion.outputs.nuGetVersion }}"
          echo "  BranchName: ${{ steps.gitversion.outputs.branchName }}"
          echo "  PreReleaseTag: '${{ steps.gitversion.outputs.preReleaseTag }}'"
          echo "  PreReleaseLabel: '${{ steps.gitversion.outputs.preReleaseLabel }}'"
          echo "  IsPreRelease: ${{ steps.gitversion.outputs.preReleaseTag != '' }}"
          echo "  CommitsSinceVersionSource: ${{ steps.gitversion.outputs.commitsSinceVersionSource }}"
          echo "  VersionSourceSha: ${{ steps.gitversion.outputs.versionSourceSha }}"
          echo ""
          echo "🔍 Branch Detection Validation:"
          echo "  GitVersion detected branch: ${{ steps.gitversion.outputs.branchName }}"
          echo "  Expected branch: $SELECTED_BRANCH"
          echo "  Match status: ${{ steps.gitversion.outputs.branchName == github.event.inputs.branch && '✅ CORRECT' || '❌ MISMATCH' }}"
          echo ""
          echo "🧪 Expected Version Behavior:"
          if [[ "$SELECTED_BRANCH" == "main" ]]; then
            echo "  Expected for main: Stable release (no pre-release suffix)"
            echo "  Expected format: v0.1.X"
          elif [[ "$SELECTED_BRANCH" == "develop" ]]; then
            echo "  Expected for develop: Beta pre-release"
            echo "  Expected format: v0.1.X-beta.Y"
          else
            echo "  Expected for $SELECTED_BRANCH: Custom branch behavior"
          fi
          echo ""
          echo "✅ Actual Version Generated: ${{ steps.gitversion.outputs.fullSemVer }}"

      - name: Validate version format matches branch expectations
        run: |
          SELECTED_BRANCH="${{ github.event.inputs.branch }}"
          GENERATED_VERSION="${{ steps.gitversion.outputs.fullSemVer }}"

          echo "🔍 Validating version format for branch: $SELECTED_BRANCH"
          echo "Generated version: $GENERATED_VERSION"

          if [[ "$SELECTED_BRANCH" == "main" ]]; then
            # For main branch: expect stable release (no pre-release suffix) with format v0.1.X
            if [[ "$GENERATED_VERSION" == *"-"* ]]; then
              echo "❌ ERROR: Main branch should generate stable release without pre-release suffix"
              echo "Expected: v0.1.X (stable release)"
              echo "Actual: $GENERATED_VERSION (contains pre-release suffix)"
              exit 1
            fi

            # Check if version follows v0.1.X pattern
            if [[ ! "$GENERATED_VERSION" =~ ^0\.1\.[0-9]+$ ]]; then
              echo "❌ ERROR: Main branch version doesn't match expected format"
              echo "Expected format: v0.1.X"
              echo "Actual: $GENERATED_VERSION"
              exit 1
            fi

            echo "✅ Version validation passed for main branch"
          elif [[ "$SELECTED_BRANCH" == "develop" ]]; then
            # For develop branch: expect beta pre-release with format v0.1.X-beta.Y
            if [[ ! "$GENERATED_VERSION" =~ ^0\.1\.[0-9]+-beta\.[0-9]+$ ]]; then
              echo "❌ ERROR: Develop branch version doesn't match expected format"
              echo "Expected format: v0.1.X-beta.Y"
              echo "Actual: $GENERATED_VERSION"
              exit 1
            fi

            echo "✅ Version validation passed for develop branch"
          else
            echo "ℹ️ Custom branch detected - skipping specific format validation"
          fi

      - name: Validate manual tag and compare with GitVersion
        id: validate_tag
        if: github.event.inputs.tag != ''
        run: |
          MANUAL_TAG="${{ github.event.inputs.tag }}"
          GITVERSION_TAG="v${{ steps.gitversion.outputs.semVer }}"

          # Semver validation
          SEMVER_REGEX="^v?(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$"
          if ! [[ $MANUAL_TAG =~ $SEMVER_REGEX ]]; then
            echo "Error: manual tag '$MANUAL_TAG' doesn't comply with SemVer standard"
            exit 1
          fi

          # remove leading 'v' for comparison
          CLEAN_MANUAL_TAG=${MANUAL_TAG#v}
          CLEAN_GITVERSION_TAG=${GITVERSION_TAG#v}

          # Split versions into components for comparison
          IFS='.' read -ra MANUAL_PARTS <<< "${CLEAN_MANUAL_TAG%-*}"
          IFS='.' read -ra GITVERSION_PARTS <<< "${CLEAN_GITVERSION_TAG%-*}"

          # Compare major.minor.patch versions
          for i in {0..2}; do
            if [[ ${MANUAL_PARTS[$i]} -lt ${GITVERSION_PARTS[$i]} ]]; then
              echo "Error: manual tag '$MANUAL_TAG' is lower as GitVersion-tag '$GITVERSION_TAG'"
              exit 1
            elif [[ ${MANUAL_PARTS[$i]} -gt ${GITVERSION_PARTS[$i]} ]]; then
              # Manual tag is higher, which is valid
              break
            fi
          done

          # Check for prerelease comparison if major.minor.patch are equal
          if [[ "${MANUAL_PARTS[0]}" == "${GITVERSION_PARTS[0]}" && "${MANUAL_PARTS[1]}" == "${GITVERSION_PARTS[1]}" && "${MANUAL_PARTS[2]}" == "${GITVERSION_PARTS[2]}" ]]; then
            # If GitVersion has no prerelease but manual has, manual is lower (invalid)
            if [[ "$CLEAN_GITVERSION_TAG" != *"-"* && "$CLEAN_MANUAL_TAG" == *"-"* ]]; then
              echo "Error: Manual Tag '$MANUAL_TAG' (Prerelease) is lower as GitVersion-tag '$GITVERSION_TAG' (Release)"
              exit 1
            fi
          fi

          echo "Manual tag '$MANUAL_TAG' valid and not lower as GitVersion-tag '$GITVERSION_TAG'"
        shell: bash

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Release
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build -o ./artifacts

      - name: Determine release type and tag
        id: release_info
        run: |
          BRANCH="${{ github.event.inputs.branch }}"

          # Use manual tag if provided, otherwise use GitVersion output
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            TAG="${{ github.event.inputs.tag }}"
            echo "Using manual tag: $TAG"
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG="${{ github.ref_name }}"
            echo "Using existing git tag: $TAG"
          else
            # Use appropriate GitVersion output based on branch
            if [[ "$BRANCH" == "main" ]]; then
              TAG="v${{ steps.gitversion.outputs.semVer }}"
              echo "Main branch - using SemVer: $TAG"
            else
              TAG="v${{ steps.gitversion.outputs.fullSemVer }}"
              echo "Non-main branch - using FullSemVer: $TAG"
            fi
          fi

          # Determine if it's a prerelease based on tag content OR branch
          if [[ "$TAG" == *"-"* ]] || [[ "$BRANCH" != "main" ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
            echo "release_name=Pre-Release" >> $GITHUB_OUTPUT
            echo "🧪 Creating Pre-Release for branch: $BRANCH (tag: $TAG)"
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
            echo "release_name=Release" >> $GITHUB_OUTPUT
            echo "📦 Creating stable Release for branch: $BRANCH (tag: $TAG)"
          fi

          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release_info.outputs.tag }}
          files: |
            ./artifacts/*.nupkg
            ./artifacts/*.snupkg
          name: ${{ steps.release_info.outputs.release_name }} ${{ steps.release_info.outputs.tag }}
          draft: false
          prerelease: ${{ steps.release_info.outputs.is_prerelease == 'true' }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload NuGet Package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: |
            ./artifacts/*.nupkg
            ./artifacts/*.snupkg
